#!/usr/bin/env python3
r"""Normalize a Trench master .tex to build under osbook.cls (impo, trench family).

Phase 2 of tasks/add-trench-differential-equations-book.md. A deterministic
LaTeX->LaTeX transform: replace the Trench `book`/dvips preamble with an osbook
preamble (loading osbook-envs + the trench-osbook shim + the book metadata), and
drop the manual `\setcounter{chapter}{N}` lines (osbook's \chapter auto-numbers).
The document body is otherwise unchanged -- aesthetics only, no mathematical
content is touched. Front matter / license is Phase 4; EPS->PDF is Phase 3.

Reads the PRISTINE master and writes a sibling `<stem>-osbook.tex`, so it is
re-runnable and never mutates the fetched source.

Paths are relative to the script or an explicit argument -- never container-absolute.
Run:  python3 tools/normalize_master.py [path/to/MASTER.tex]
      (default: ../checkout/TRENCH_DIFFEQ.tex, relative to this script)
"""
from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path

OSBOOK_PREAMBLE: str = r"""% Auto-generated by tools/normalize_master.py -- osbook restyle of Trench's
% Elementary Differential Equations. The original book/dvips preamble AND the
% hand-typed title/license/contents front matter (up to the Preface) are replaced:
% the preamble by this osbook preamble, the front matter by \OSfrontmatter with
% Trench's CC BY-NC-SA 3.0 license + the "TO BEVERLY" dedication. The Preface and
% every chapter are kept unchanged, except the manual \setcounter{chapter}{N}
% lines are dropped (osbook \chapter auto-numbers). EPS figures come from Phase 3.
\documentclass[letter]{osbook}
\usepackage{osbook-envs}
\usepackage{trench-osbook}
\graphicspath{{converted_graphics/}{EPS/}{EPS-pdf/}}
\setOSbooktitle{Elementary Differential Equations}
\setOSbooksubtitle{Formatted by Bill Six}
\setOSbookpublisher{}
\setOSbookdedication{TO BEVERLY}
\setOSbooklicense{%
  \emph{Elementary Differential Equations} by William F. Trench (Andrew G. Cowles
  Distinguished Professor Emeritus, Department of Mathematics, Trinity University).
  This book has been judged to meet the evaluation criteria set by the Editorial
  Board of the American Institute of Mathematics in connection with the Institute's
  Open Textbook Initiative. It may be copied, modified, redistributed, translated,
  and built upon subject to the Creative Commons
  Attribution-NonCommercial-ShareAlike 3.0 Unported License (CC BY-NC-SA 3.0).\par
  \medskip
  \noindent Free Edition 1.01 (December 2013). This book was published previously
  by Brooks/Cole Thomson Learning, 2001. This free edition is made available in the
  hope that it will be useful as a textbook or reference. Reproduction is permitted
  for any valid noncommercial educational, mathematical, or scientific purpose;
  charges for profit beyond reasonable printing costs are prohibited.\par
  \medskip
  \noindent Typeset with \LaTeX\ in the OpenStax house style, formatted by Bill Six.}
\begin{document}
\OSfrontmatter
"""


def about_this_edition() -> str:
    r"""The "About This Edition" front-matter colophon for the trench book: formatted
    by Bill Six, the impo toolchain + build commit SHA + date, and a pointer to the
    CC BY-NC-SA 3.0 license page. `\chapter*` (NOT `\chapter`) because it sits after
    `\OSfrontmatter`'s `\mainmatter`, so a plain `\chapter` would step the counter and
    shift "Chapter 1"; starred = unnumbered + no increment, `\addcontentsline` keeps it
    in the TOC. The impo commit SHA + date come from IMPO_COMMIT / IMPO_BUILD_DATE, or,
    since this runs on the host in the impo repo, fall back to `git rev-parse HEAD`."""
    sha: str = os.environ.get("IMPO_COMMIT", "").strip()
    if not sha:
        try:
            sha = subprocess.check_output(
                ["git", "rev-parse", "HEAD"], cwd=str(Path(__file__).resolve().parent)
            ).decode().strip()
        except (OSError, subprocess.CalledProcessError):
            sha = ""
    date: str = os.environ.get("IMPO_BUILD_DATE", "").strip()
    if sha:
        built: str = ", built from commit \\texttt{%s}" % sha
        if date:
            built += " on %s" % date
    else:
        built = " (a local development build)"
    return (
        "\\chapter*{About This Edition}\n"
        "\\addcontentsline{toc}{chapter}{About This Edition}\n"
        "This edition of \\emph{Elementary Differential Equations} by William F. Trench "
        "was formatted by William Emerison Six (``Bill~Six'') using the \\emph{impo} "
        "toolchain (\\href{https://github.com/billsix/impo}{github.com/billsix/impo})%s.\n\n"
        "\\medskip\\noindent The text and figures are \\textcopyright{} William F. Trench, "
        "licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 3.0 "
        "Unported License (CC~BY-NC-SA~3.0); see the license page above. The impo "
        "toolchain and this LaTeX formatting are \\textcopyright{} William Emerison Six, "
        "released under the MIT License.\n\n" % built
    )


def normalize(text: str) -> str:
    # 1. Cut point = the Preface bookmark. Everything BEFORE it (the book/dvips
    #    preamble + hand title/license/dedication/contents) is replaced by the
    #    osbook preamble + \OSfrontmatter; the Preface and all chapters are kept.
    m: re.Match[str] | None = re.search(r"\\pdfbookmark\[0\]\{Preface\}", text)
    if m is None:
        raise SystemExit("normalize: Preface marker not found (front-matter cut point)")
    body: str = text[m.start():]
    # 2. Drop the manual chapter-counter setters (osbook \chapter auto-numbers).
    body = re.sub(r"^[ \t]*\\setcounter\{chapter\}\{\d+\}[ \t]*\n", "", body, flags=re.M)
    # 3. Body fixups:
    #    (a) \enlargethispage{1\in} -- \in is the math ∈ symbol, not a length unit;
    #        the author meant 1in.
    body = body.replace(r"\enlargethispage{1\in}", r"\enlargethispage{1in}")
    #    (b) Strip the EPS bounding box from every \includegraphics. Trench stamps
    #        the SAME bb (bb=-78 148 689 643) on every figure -- an artifact of the
    #        EPS/dvips pipeline. epstopdf already crops each PDF to its own real box
    #        at origin (0,0), so re-declaring a non-zero-origin bb OFFSETS the image
    #        (down/right, overlapping the caption). Remove bb= and let graphicx use
    #        each PDF's MediaBox; the width/height/keepaspectratio still size it.
    body = re.sub(r"bb\s*=\s*-?[\d.]+\s+-?[\d.]+\s+-?[\d.]+\s+-?[\d.]+\s*,?\s*", "", body)
    #    (c) Cap figure width at the text block. Trench sizes figures at 5.67in but
    #        the osbook measure is 5in, so wide figures overflowed the right margin
    #        (many Overfull \hbox). adjustbox's [export] `max width` key (loaded by
    #        the shim) constrains each figure to \linewidth while keeping smaller
    #        ones at their intended size.
    body = body.replace(r"\includegraphics[", r"\includegraphics[max width=\linewidth,")
    #    (d) `\l` in math is a source typo for `\ell` (ℓ): the author writes `\l`
    #        and `\ell` interchangeably in adjacent exercises, and `\l` (Polish ł) is
    #        invalid in math ("Missing character ł in cmmi10"). Replace a bare `\l`
    #        (not part of a longer control word like \ldots/\linewidth/\ll) with \ell.
    body = re.sub(r"\\l(?![a-zA-Z])", r"\\ell", body)
    # Insert the "About This Edition" colophon right after \OSfrontmatter (the last
    # line of OSBOOK_PREAMBLE), before the Preface -- the first front-matter unit.
    return OSBOOK_PREAMBLE + about_this_edition() + body


def main() -> None:
    default: Path = Path(__file__).resolve().parents[1] / "checkout" / "TRENCH_DIFFEQ.tex"
    src: Path = Path(sys.argv[1]) if len(sys.argv) > 1 else default
    if not src.exists():
        raise SystemExit(f"normalize: master not found: {src}")
    out: Path = src.with_name(src.stem + "-osbook.tex")
    out.write_text(normalize(src.read_text(encoding="utf-8")), encoding="utf-8")
    print(f"normalize: wrote {out}")


if __name__ == "__main__":
    main()
